version: '3.6'

services:
  db:
    image: postgres:14
    volumes:
      - db-test-volume:/var/lib/postgresql/data
      - ./postgres/initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgresdb
    ports:
      - 5432:5432

  api:
    build:
      context: ./spring/
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ../api:/app
    ports:
      - 8080:8080
    depends_on:
      - db
    tty: true

  front:
    build: 
      context: ./react/
      dockerfile: Dockerfile
    volumes:
      - ../front:/usr/src/app
    command: sh -c "cd react-sample && yarn start"
    ports:
      - "8000:8080"
    environment:
      - WDS_SOCKET_PORT=0 #if you have socket error, need to wirte

volumes:
  db-test-volume: